language: node_js
cache:
  directories:
    - $HOME/.rvm
    - $HOME/.vvm
notifications:
  email: false
before_install:
  - sudo apt-get install -qq vim
  - npm install
  -
  - curl https://raw.githubusercontent.com/kana/vim-version-manager/master/bin/vvm | python - setup; true
  - source ~/.vvm/etc/login
  - vvm update_itself
  - vvm use vimorg--v8.0.1529 --install --with-features=huge
  -
  - rvm use 2.5.0 --install --binary --fuzzy
  - bundle install
script: npm test
